"""create core data model

Revision ID: 9a2add58b5be
Revises:
Create Date: 2026-04-28 00:33:06.145714
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "9a2add58b5be"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_totals",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("kcal", sa.Float(), server_default="0", nullable=False),
        sa.Column("carbs_g", sa.Float(), server_default="0", nullable=False),
        sa.Column("protein_g", sa.Float(), server_default="0", nullable=False),
        sa.Column("fat_g", sa.Float(), server_default="0", nullable=False),
        sa.Column("fiber_g", sa.Float(), server_default="0", nullable=False),
        sa.Column("meal_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "estimated_item_count", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("exact_item_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("date"),
    )
    op.create_table(
        "meals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("eaten_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft", "accepted", "discarded", name="meal_status", native_enum=False
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum(
                "photo",
                "pattern",
                "manual",
                "mixed",
                name="meal_source",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("total_carbs_g", sa.Float(), server_default="0", nullable=False),
        sa.Column("total_protein_g", sa.Float(), server_default="0", nullable=False),
        sa.Column("total_fat_g", sa.Float(), server_default="0", nullable=False),
        sa.Column("total_fiber_g", sa.Float(), server_default="0", nullable=False),
        sa.Column("total_kcal", sa.Float(), server_default="0", nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("nightscout_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("nightscout_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name="ck_meals_confidence_range",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_meals_eaten_at", "meals", ["eaten_at"], unique=False)
    op.create_table(
        "patterns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("prefix", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("default_grams", sa.Float(), nullable=True),
        sa.Column("default_carbs_g", sa.Float(), server_default="0", nullable=False),
        sa.Column("default_protein_g", sa.Float(), server_default="0", nullable=False),
        sa.Column("default_fat_g", sa.Float(), server_default="0", nullable=False),
        sa.Column("default_fiber_g", sa.Float(), server_default="0", nullable=False),
        sa.Column("default_kcal", sa.Float(), server_default="0", nullable=False),
        sa.Column("source_url", sa.String(), nullable=True),
        sa.Column("usage_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_archived", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("prefix", "key", name="uq_patterns_prefix_key"),
    )
    op.create_index("ix_patterns_prefix", "patterns", ["prefix"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("barcode", sa.String(), nullable=True),
        sa.Column("brand", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("default_grams", sa.Float(), nullable=True),
        sa.Column("default_serving_text", sa.String(), nullable=True),
        sa.Column("carbs_per_100g", sa.Float(), nullable=True),
        sa.Column("protein_per_100g", sa.Float(), nullable=True),
        sa.Column("fat_per_100g", sa.Float(), nullable=True),
        sa.Column("fiber_per_100g", sa.Float(), nullable=True),
        sa.Column("kcal_per_100g", sa.Float(), nullable=True),
        sa.Column("carbs_per_serving", sa.Float(), nullable=True),
        sa.Column("protein_per_serving", sa.Float(), nullable=True),
        sa.Column("fat_per_serving", sa.Float(), nullable=True),
        sa.Column("fiber_per_serving", sa.Float(), nullable=True),
        sa.Column("kcal_per_serving", sa.Float(), nullable=True),
        sa.Column("source_kind", sa.String(), server_default="manual", nullable=False),
        sa.Column("source_url", sa.String(), nullable=True),
        sa.Column("usage_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_products_barcode", "products", ["barcode"], unique=False)
    op.create_table(
        "ai_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("meal_id", sa.Uuid(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("prompt_version", sa.String(), nullable=False),
        sa.Column("request_summary", sa.JSON(), nullable=True),
        sa.Column("response_raw", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["meal_id"], ["meals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_ai_runs_meal_id", "ai_runs", ["meal_id"], unique=False)
    op.create_table(
        "pattern_aliases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pattern_id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["pattern_id"], ["patterns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "pattern_id", "alias", name="uq_pattern_aliases_pattern_alias"
        ),
    )
    op.create_index(
        "ix_pattern_aliases_alias", "pattern_aliases", ["alias"], unique=False
    )
    op.create_index(
        "ix_pattern_aliases_pattern_id", "pattern_aliases", ["pattern_id"], unique=False
    )
    op.create_table(
        "photos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("meal_id", sa.Uuid(), nullable=False),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("original_filename", sa.String(), nullable=True),
        sa.Column("content_type", sa.String(), nullable=True),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "scenario",
            sa.Enum(
                "label_full",
                "label_partial",
                "plated",
                "barcode",
                "reference",
                "unknown",
                name="photo_scenario",
                native_enum=False,
            ),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column(
            "has_reference_object", sa.Boolean(), server_default="0", nullable=False
        ),
        sa.Column(
            "reference_kind",
            sa.Enum(
                "coin_5rub",
                "card",
                "hand",
                "fork",
                "plate",
                "none",
                name="photo_reference_kind",
                native_enum=False,
            ),
            server_default="none",
            nullable=False,
        ),
        sa.Column("gemini_response_raw", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["meal_id"], ["meals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_photos_meal_id", "photos", ["meal_id"], unique=False)
    op.create_table(
        "product_aliases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("alias", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "product_id", "alias", name="uq_product_aliases_product_alias"
        ),
    )
    op.create_index(
        "ix_product_aliases_alias", "product_aliases", ["alias"], unique=False
    )
    op.create_index(
        "ix_product_aliases_product_id", "product_aliases", ["product_id"], unique=False
    )
    op.create_table(
        "meal_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("meal_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("brand", sa.String(), nullable=True),
        sa.Column("grams", sa.Float(), nullable=True),
        sa.Column("serving_text", sa.String(), nullable=True),
        sa.Column("carbs_g", sa.Float(), server_default="0", nullable=False),
        sa.Column("protein_g", sa.Float(), server_default="0", nullable=False),
        sa.Column("fat_g", sa.Float(), server_default="0", nullable=False),
        sa.Column("fiber_g", sa.Float(), server_default="0", nullable=False),
        sa.Column("kcal", sa.Float(), server_default="0", nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("confidence_reason", sa.String(), nullable=True),
        sa.Column(
            "source_kind",
            sa.Enum(
                "photo_estimate",
                "label_calc",
                "restaurant_db",
                "product_db",
                "pattern",
                "manual",
                name="item_source_kind",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("calculation_method", sa.String(), nullable=True),
        sa.Column(
            "assumptions", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column(
            "evidence", sa.JSON(), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column(
            "warnings", sa.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column("pattern_id", sa.Uuid(), nullable=True),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("photo_id", sa.Uuid(), nullable=True),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name="ck_meal_items_confidence_range",
        ),
        sa.ForeignKeyConstraint(["meal_id"], ["meals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["pattern_id"],
            ["patterns.id"],
        ),
        sa.ForeignKeyConstraint(
            ["photo_id"],
            ["photos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_meal_items_meal_id", "meal_items", ["meal_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_meal_items_meal_id", table_name="meal_items")
    op.drop_table("meal_items")
    op.drop_index("ix_product_aliases_product_id", table_name="product_aliases")
    op.drop_index("ix_product_aliases_alias", table_name="product_aliases")
    op.drop_table("product_aliases")
    op.drop_index("ix_photos_meal_id", table_name="photos")
    op.drop_table("photos")
    op.drop_index("ix_pattern_aliases_pattern_id", table_name="pattern_aliases")
    op.drop_index("ix_pattern_aliases_alias", table_name="pattern_aliases")
    op.drop_table("pattern_aliases")
    op.drop_index("ix_ai_runs_meal_id", table_name="ai_runs")
    op.drop_table("ai_runs")
    op.drop_index("ix_products_barcode", table_name="products")
    op.drop_table("products")
    op.drop_index("ix_patterns_prefix", table_name="patterns")
    op.drop_table("patterns")
    op.drop_index("ix_meals_eaten_at", table_name="meals")
    op.drop_table("meals")
    op.drop_table("daily_totals")
    # ### end Alembic commands ###
