"""add_calorie_breakdown_to_daily_activity

Revision ID: d51c2bbf9096
Revises: f1a2b3c4d5e6
Create Date: 2026-05-02 03:10:49.259908
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'd51c2bbf9096'
down_revision: str | None = 'f1a2b3c4d5e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_activity', sa.Column('hr_samples', sa.Integer(), server_default='0', nullable=False))
    op.add_column('daily_activity', sa.Column('hr_active_minutes', sa.Integer(), server_default='0', nullable=False))
    op.add_column('daily_activity', sa.Column('kcal_hr_active', sa.Float(), server_default='0', nullable=False))
    op.add_column('daily_activity', sa.Column('kcal_steps', sa.Float(), server_default='0', nullable=False))
    op.add_column('daily_activity', sa.Column('kcal_no_move_hr', sa.Float(), server_default='0', nullable=False))
    op.add_column('daily_activity', sa.Column('calorie_confidence', sa.String(length=16), server_default='none', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_activity', 'calorie_confidence')
    op.drop_column('daily_activity', 'kcal_no_move_hr')
    op.drop_column('daily_activity', 'kcal_steps')
    op.drop_column('daily_activity', 'kcal_hr_active')
    op.drop_column('daily_activity', 'hr_active_minutes')
    op.drop_column('daily_activity', 'hr_samples')
    # ### end Alembic commands ###
