import { http, HttpResponse } from "msw";
import { setupServer } from "msw/node";

const now = "2026-04-28T10:00:00.000Z";

const mealResponse = (overrides: Record<string, unknown> = {}) => ({
  id: "meal-1",
  eaten_at: now,
  title: "Test meal",
  note: null,
  status: "accepted",
  source: "manual",
  total_carbs_g: 0,
  total_protein_g: 0,
  total_fat_g: 0,
  total_fiber_g: 0,
  total_kcal: 0,
  confidence: null,
  nightscout_synced_at: null,
  nightscout_id: null,
  created_at: now,
  updated_at: now,
  items: [],
  photos: [],
  ...overrides,
});

export const server = setupServer(
  http.get("http://api.test/health", () =>
    HttpResponse.json({ status: "ok", version: "0.1.0", db: "ok" }),
  ),
  http.get("http://api.test/openapi.json", () =>
    HttpResponse.json({ openapi: "3.1.0", info: { version: "0.1.0" } }),
  ),
  http.get("http://api.test/nightscout/status", () =>
    HttpResponse.json({ configured: false, status: null }),
  ),
  http.get("http://api.test/nightscout/latest-reading", () =>
    HttpResponse.json({
      timestamp: null,
      value_mmol_l: null,
      trend: null,
      sensor_id: null,
      total_entries: 0,
    }),
  ),
  http.get("http://api.test/settings/nightscout", () =>
    HttpResponse.json({
      enabled: false,
      configured: false,
      connected: false,
      url: null,
      secret_is_set: false,
      last_status_check_at: null,
      last_error: null,
      sync_glucose: true,
      show_glucose_in_journal: true,
      import_insulin_events: true,
      allow_meal_send: true,
      confirm_before_send: true,
      autosend_meals: false,
    }),
  ),
  http.put("http://api.test/settings/nightscout", async ({ request }) => {
    const body = (await request.json()) as Record<string, unknown>;
    return HttpResponse.json({
      enabled: Boolean(body.nightscout_enabled),
      configured: Boolean(body.nightscout_url && body.nightscout_api_secret),
      connected: false,
      url: body.nightscout_url ?? null,
      secret_is_set: Boolean(body.nightscout_api_secret),
      last_status_check_at: null,
      last_error: null,
      sync_glucose: body.sync_glucose ?? true,
      show_glucose_in_journal: body.show_glucose_in_journal ?? true,
      import_insulin_events: body.import_insulin_events ?? true,
      allow_meal_send: body.allow_meal_send ?? true,
      confirm_before_send: body.confirm_before_send ?? true,
      autosend_meals: body.autosend_meals ?? false,
    });
  }),
  http.post("http://api.test/settings/nightscout/test", () =>
    HttpResponse.json({
      ok: false,
      status: null,
      server_name: null,
      version: null,
      error: "Nightscout не подключён",
    }),
  ),
  http.get("http://api.test/nightscout/day_status", () =>
    HttpResponse.json({
      connected: false,
      configured: false,
      accepted_meals_count: 0,
      unsynced_meals_count: 0,
      synced_meals_count: 0,
      failed_meals_count: 0,
      last_sync_at: null,
    }),
  ),
  http.post("http://api.test/nightscout/sync/today", async ({ request }) => {
    const body = (await request.json()) as Record<string, unknown>;
    return HttpResponse.json({
      date: body.date ?? "2026-04-28",
      total_candidates: 0,
      sent_count: 0,
      skipped_count: 0,
      failed_count: 0,
      results: [],
    });
  }),
  http.get("http://api.test/nightscout/events", () =>
    HttpResponse.json({ glucose: [], insulin: [] }),
  ),
  http.post("http://api.test/nightscout/import", () =>
    HttpResponse.json({
      from_datetime: "2026-04-28T00:00:00",
      to_datetime: "2026-04-28T23:59:59",
      glucose_count: 0,
      insulin_count: 0,
    }),
  ),
  http.get("http://api.test/timeline", () =>
    HttpResponse.json({
      from_datetime: "2026-04-28T00:00:00",
      to_datetime: "2026-04-28T23:59:59",
      episodes: [],
      ungrouped_insulin: [],
    }),
  ),
  http.get("http://api.test/profile", () =>
    HttpResponse.json({
      weight_kg: null,
      height_cm: null,
      age_years: null,
      sex: null,
      activity_level: "moderate",
    }),
  ),
  http.put("http://api.test/profile", async ({ request }) => {
    const body = (await request.json()) as Record<string, unknown>;
    return HttpResponse.json({
      weight_kg: body.weight_kg ?? null,
      height_cm: body.height_cm ?? null,
      age_years: body.age_years ?? null,
      sex: body.sex ?? null,
      activity_level: body.activity_level ?? "moderate",
    });
  }),
  http.get("http://api.test/me/schedule", () =>
    HttpResponse.json({
      anchor_weekday_minutes: null,
      anchor_weekend_minutes: null,
      effective_anchor_minutes: null,
      basis: null,
      user_override_minutes: null,
      last_shift_at: null,
      windows: [],
      history: [],
      non_typical_periods: [],
    }),
  ),
  http.get("http://api.test/activity/balance", ({ request }) =>
    HttpResponse.json({
      date: new URL(request.url).searchParams.get("day") ?? "2026-04-28",
      kcal_in: 0,
      kcal_burned: 0,
      tdee: null,
      net_balance: null,
      steps: 0,
      bmr_available: false,
    }),
  ),
  http.get("http://api.test/activity/balance/range", () =>
    HttpResponse.json({ days: [] }),
  ),
  http.get("http://api.test/reports/endocrinologist", () =>
    HttpResponse.json({
      app_name: "glucotracker",
      title: "Отчёт для эндокринолога",
      glucose_mode: "raw",
      glucose_mode_label: "исходная CGM",
      period_label: "Период: 28 апреля 2026",
      generated_label: "Сгенерировано: 29 апреля 2026",
      chips: [
        { label: "1 дней" },
        { label: "0/1 дней с едой" },
        { label: "CGM coverage —" },
        { label: "0 пищевых эпизода" },
      ],
      warning: "Данных мало: 0 дней с едой из 1 выбранных",
      notes: ["CGM нет за период", "Инсулин не найден"],
      kpis: [
        {
          label: "ИНСУЛИН ЗАВТРАК",
          value: "—",
          unit: "",
          caption: "медиана за период",
        },
        {
          label: "ИНСУЛИН ОБЕД",
          value: "—",
          unit: "",
          caption: "медиана за период",
        },
        {
          label: "ИНСУЛИН УЖИН",
          value: "—",
          unit: "",
          caption: "медиана за период",
        },
        {
          label: "ИНСУЛИН ЗА ДЕНЬ",
          value: "—",
          unit: "",
          caption: "медиана за период",
        },
        {
          label: "САХАР ДО ЕДЫ",
          value: "—",
          unit: "",
          caption: "медиана за период",
        },
        {
          label: "САХАР ПОСЛЕ ЕДЫ",
          value: "—",
          unit: "",
          caption: "медиана за период",
        },
        {
          label: "НАБЛЮДАЕМЫЙ УК",
          value: "—",
          unit: "",
          caption: "по всем эпизодам",
        },
        {
          label: "TIR 3.9-10.0",
          value: "—",
          unit: "",
          caption: "CGM нет",
        },
      ],
      meal_profile_rows: [],
      daily_rows: [],
      shown_daily_rows: [],
      daily_median_row: {
        date: "median",
        date_label: "Медиана",
        carbs: "—",
        insulin: "—",
        tir: "—",
        hypo: "0",
        breakfast: "—",
        lunch: "—",
        dinner: "—",
        flagged: false,
      },
      daily_rows_note: null,
      bottom_metrics: [],
      footer:
        "Инсулин получен из Nightscout (только чтение). Отчёт информационный и не является медицинской рекомендацией.",
    }),
  ),
  http.get("http://api.test/meals", () =>
    HttpResponse.json({ items: [], total: 0, limit: 20, offset: 0 }),
  ),
  http.post("http://api.test/meals", async ({ request }) => {
    const body = (await request.json()) as Record<string, unknown>;
    return HttpResponse.json(mealResponse(body), { status: 201 });
  }),
  http.get("http://api.test/meals/:mealId", () =>
    HttpResponse.json(mealResponse()),
  ),
  http.patch("http://api.test/meals/:mealId", async ({ request }) => {
    const body = (await request.json()) as Record<string, unknown>;
    return HttpResponse.json(mealResponse(body));
  }),
  http.delete("http://api.test/meals/:mealId", () =>
    HttpResponse.json({ deleted: true }),
  ),
  http.put("http://api.test/meals/:mealId/items", async ({ request }) => {
    const items = await request.json();
    return HttpResponse.json(mealResponse({ items }));
  }),
  http.patch("http://api.test/meal_items/:itemId", async ({ params, request }) => {
    const body = (await request.json()) as Record<string, unknown>;
    return HttpResponse.json({
      id: params.itemId,
      meal_id: "meal-1",
      name: "Coffee",
      brand: null,
      grams: null,
      serving_text: null,
      carbs_g: 0,
      protein_g: 0,
      fat_g: 0,
      fiber_g: 0,
      kcal: 0,
      confidence: null,
      confidence_reason: null,
      source_kind: "manual",
      calculation_method: null,
      assumptions: [],
      evidence: {},
      warnings: [],
      nutrients: [],
      pattern_id: null,
      product_id: null,
      photo_id: null,
      position: 0,
      created_at: now,
      updated_at: now,
      image_url: null,
      image_cache_path: null,
      source_image_url: null,
      ...body,
    });
  }),
  http.get("http://api.test/autocomplete", () =>
    HttpResponse.json([
      {
        kind: "pattern",
        id: "pattern-1",
        token: "bk:whopper",
        display_name: "Whopper",
        subtitle: "bk:whopper",
        carbs_g: 51,
        protein_g: 28,
        fat_g: 35,
        kcal: 635,
        image_url: "https://example.test/whopper.png",
        usage_count: 7,
        matched_alias: "whopper",
      },
    ]),
  ),
  http.get("http://api.test/database/items", ({ request }) => {
    const query = new URL(request.url).searchParams.get("q") ?? "";
    const allItems = [
      {
        id: "pattern-1",
        kind: "restaurant",
        prefix: "bk",
        key: "whopper",
        token: "bk:whopper",
        display_name: "Whopper",
        subtitle: "bk:whopper",
        image_url: "https://example.test/whopper.png",
        image_cache_path: null,
        carbs_g: 51,
        protein_g: 28,
        fat_g: 35,
        fiber_g: 3,
        kcal: 635,
        default_grams: 270,
        usage_count: 7,
        last_used_at: "2026-04-28T10:00:00.000Z",
        source_name: "Burger King",
        source_url: "https://origin.bk.com/pdfs/nutrition.pdf",
        source_confidence: null,
        is_verified: false,
        aliases: ["воппер", "whopper"],
        nutrients_json: { sodium_mg: { amount: 980, unit: "mg" } },
        quality_warnings: [],
      },
      {
        id: "product-1",
        kind: "product",
        prefix: null,
        key: null,
        token: "4601234567890",
        display_name: "Protein Drink",
        subtitle: "Example · 4601234567890",
        image_url: "https://example.test/drink.png",
        image_cache_path: null,
        carbs_g: 12,
        protein_g: 25,
        fat_g: 2,
        fiber_g: 1,
        kcal: 166,
        default_grams: 330,
        usage_count: 2,
        last_used_at: null,
        source_name: "Example",
        source_url: null,
        source_confidence: null,
        is_verified: false,
        aliases: ["drink"],
        nutrients_json: {},
        quality_warnings: ["нужно проверить"],
      },
    ];
    const items = query
      ? allItems.filter((item) =>
          [item.display_name, item.token, item.subtitle, ...item.aliases]
            .filter(Boolean)
            .some((value) => value.toLowerCase().includes(query.toLowerCase())),
        )
      : allItems;
    return HttpResponse.json({
      items,
      total: items.length,
      limit: 100,
      offset: 0,
    });
  }),
  http.post("http://api.test/meals/:mealId/photos", () =>
    HttpResponse.json(
      {
        id: "photo-1",
        meal_id: "meal-1",
        path: "2026/04/photo-1.jpg",
        original_filename: "photo.jpg",
        content_type: "image/jpeg",
        taken_at: null,
        scenario: "unknown",
        has_reference_object: false,
        reference_kind: "none",
        gemini_response_raw: null,
        created_at: now,
      },
      { status: 201 },
    ),
  ),
  http.get("http://api.test/photos/:photoId/file", () =>
    HttpResponse.text("image-bytes", {
      headers: { "Content-Type": "image/jpeg" },
    }),
  ),
  http.post("http://api.test/meals/:mealId/estimate_and_save_draft", () =>
    HttpResponse.json({
      meal_id: "meal-1",
      source_photos: [
        {
          id: "photo-1",
          url: "/photos/photo-1/file",
          thumbnail_url: "/photos/photo-1/file",
        },
      ],
      suggested_items: [
        {
          name: "Chicken and potatoes",
          carbs_g: 34,
          protein_g: 28,
          fat_g: 12,
          fiber_g: 4,
          kcal: 360,
          confidence: 0.55,
          confidence_reason: "Clear plate, but portion size is uncertain.",
          source_kind: "photo_estimate",
          calculation_method: "visual_estimate_gemini_mid",
          assumptions: ["Portion estimated from plate size."],
          evidence: { scenario: "PLATED" },
          warnings: [],
          position: 0,
        },
      ],
      suggested_totals: {
        total_carbs_g: 34,
        total_protein_g: 28,
        total_fat_g: 12,
        total_fiber_g: 4,
        total_kcal: 360,
      },
      calculation_breakdowns: [
        {
          position: 0,
          name: "Chicken and potatoes",
          count_detected: null,
          net_weight_per_unit_g: null,
          total_weight_g: 300,
          nutrition_per_100g: null,
          calculated_per_unit: null,
          calculated_total: {
            carbs_g: 34,
            protein_g: 28,
            fat_g: 12,
            fiber_g: 4,
            kcal: 360,
          },
          calculation_steps: [],
          evidence: ["Visible plate with chicken and potatoes."],
          assumptions: ["Portion estimated from plate size."],
        },
      ],
      gemini_notes: "Draft generated.",
      image_quality_warnings: [],
      reference_detected: "plate",
      ai_run_id: "ai-run-1",
    }),
  ),
  http.post("http://api.test/meals/:mealId/accept", async ({ request }) => {
    const body = (await request.json()) as { items?: unknown[] };
    return HttpResponse.json(
      mealResponse({
        status: "accepted",
        source: "photo",
        items: body.items ?? [],
      }),
    );
  }),
  http.post("http://api.test/meals/:mealId/discard", () =>
    HttpResponse.json(mealResponse({ status: "discarded" })),
  ),
  http.get("http://api.test/dashboard/today", () =>
    HttpResponse.json({
      date: "2026-04-28",
      kcal: 0,
      carbs_g: 0,
      protein_g: 0,
      fat_g: 0,
      fiber_g: 0,
      meal_count: 0,
      last_meal_at: null,
      hours_since_last_meal: null,
      week_avg_carbs: 0,
      week_avg_kcal: 0,
      prev_week_avg_carbs: 0,
      prev_week_avg_kcal: 0,
    }),
  ),
  http.get("http://api.test/dashboard/range", () =>
    HttpResponse.json({
      days: [],
      summary: {
        avg_kcal: 0,
        avg_carbs_g: 0,
        avg_protein_g: 0,
        avg_fat_g: 0,
        avg_fiber_g: 0,
        total_kcal: 0,
        total_carbs_g: 0,
        total_protein_g: 0,
        total_fat_g: 0,
        total_fiber_g: 0,
        total_meals: 0,
      },
    }),
  ),
  http.get("http://api.test/dashboard/heatmap", () =>
    HttpResponse.json({ cells: [] }),
  ),
  http.get("http://api.test/dashboard/top_patterns", () =>
    HttpResponse.json([]),
  ),
  http.get("http://api.test/dashboard/source_breakdown", () =>
    HttpResponse.json({ days: 7, items: [] }),
  ),
  http.get("http://api.test/dashboard/data_quality", () =>
    HttpResponse.json({
      exact_label_count: 0,
      assumed_label_count: 0,
      restaurant_db_count: 0,
      product_db_count: 0,
      pattern_count: 0,
      visual_estimate_count: 0,
      manual_count: 0,
      low_confidence_count: 0,
      total_item_count: 0,
      low_confidence_items: [],
    }),
  ),
  http.get("http://api.test/glucose/dashboard", ({ request }) => {
    const mode = new URL(request.url).searchParams.get("mode") ?? "raw";
    const sensor = {
      id: "sensor-1",
      source: "manual",
      vendor: "Ottai",
      model: "Ottai",
      label: "Sensor A",
      started_at: "2026-04-28T00:00:00",
      ended_at: null,
      expected_life_days: 15,
      notes: null,
      created_at: now,
      updated_at: now,
    };
    const quality = {
      sensor,
      sensor_age_days: 1.4,
      fingerstick_count: 1,
      valid_calibration_points: 0,
      median_bias_mmol_l: null,
      mad_mmol_l: null,
      mard_percent: null,
      drift_mmol_l_per_day: 0,
      residual_mad_mmol_l: null,
      missing_data_pct: 8,
      suspected_compression_count: 0,
      noise_score: 4,
      quality_score: 72,
      confidence: "none",
      notes: [],
      active_model: null,
    };
    return HttpResponse.json({
      from_datetime: "2026-04-28T04:00:00",
      to_datetime: "2026-04-28T10:00:00",
      mode,
      points: [
        {
          timestamp: "2026-04-28T08:00:00",
          raw_value: 6,
          smoothed_value: 6.1,
          normalized_value: 6.8,
          display_value: mode === "normalized" ? 6.8 : 6,
          correction_mmol_l: 0.8,
          flags: [],
        },
        {
          timestamp: "2026-04-28T08:05:00",
          raw_value: 6.2,
          smoothed_value: 6.2,
          normalized_value: 7,
          display_value: mode === "normalized" ? 7 : 6.2,
          correction_mmol_l: 0.8,
          flags: [],
        },
      ],
      fingersticks: [
        {
          id: "fingerstick-1",
          measured_at: "2026-04-28T08:03:00",
          glucose_mmol_l: 6.9,
          meter_name: "Contour",
          notes: null,
          created_at: now,
        },
      ],
      food_events: [
        {
          timestamp: "2026-04-28T08:10:00",
          title: "Breakfast",
          carbs_g: 42,
          kcal: 380,
        },
      ],
      insulin_events: [
        {
          timestamp: "2026-04-28T08:08:00",
          insulin_units: 4,
          event_type: "Meal Bolus",
          notes: null,
        },
      ],
      artifacts: [],
      current_sensor: sensor,
      sensors: [sensor],
      quality,
      summary: {
        current_glucose: mode === "normalized" ? 7 : 6.2,
        current_glucose_at: "2026-04-28T08:05:00",
        sensor_age_days: 1.4,
        bias_mmol_l: null,
        drift_mmol_l_per_day: 0,
        calibration_confidence: "none",
        suspected_compression_count: 0,
      },
      notes: ["Недостаточно записей из пальца для нормализации."],
    });
  }),
  http.get("http://api.test/fingersticks", () =>
    HttpResponse.json([
      {
        id: "fingerstick-1",
        measured_at: "2026-04-28T08:03:00",
        glucose_mmol_l: 6.9,
        meter_name: "Contour",
        notes: null,
        created_at: now,
      },
    ]),
  ),
  http.post("http://api.test/fingersticks", async ({ request }) => {
    const body = (await request.json()) as Record<string, unknown>;
    return HttpResponse.json(
      {
        id: "fingerstick-created",
        created_at: now,
        ...body,
      },
      { status: 201 },
    );
  }),
  http.post("http://api.test/meal_items/:itemId/copy_by_weight", async ({ params, request }) => {
    const body = (await request.json()) as Record<string, unknown>;
    const grams = Number(body.grams ?? 0);
    return HttpResponse.json(
      {
        id: "meal-from-weight",
        eaten_at: body.eaten_at ?? now,
        title: "Повтор по весу",
        note: null,
        status: "accepted",
        source: "manual",
        total_carbs_g: grams,
        total_protein_g: 0,
        total_fat_g: 0,
        total_fiber_g: 0,
        total_kcal: grams * 2,
        confidence: null,
        nightscout_synced_at: null,
        nightscout_id: null,
        nightscout_sync_status: "not_synced",
        nightscout_sync_error: null,
        nightscout_last_attempt_at: null,
        thumbnail_url: null,
        created_at: now,
        updated_at: now,
        items: [
          {
            id: `${params.itemId}-scaled`,
            meal_id: "meal-from-weight",
            name: "Повтор по весу",
            brand: null,
            grams,
            serving_text: `${grams} г`,
            carbs_g: grams,
            protein_g: 0,
            fat_g: 0,
            fiber_g: 0,
            kcal: grams * 2,
            confidence: null,
            confidence_reason: null,
            source_kind: "manual",
            calculation_method: "scaled_from_history_per_100g",
            assumptions: [],
            evidence: {},
            warnings: [],
            pattern_id: null,
            product_id: null,
            photo_id: null,
            image_url: null,
            image_cache_path: null,
            source_image_url: null,
            position: 0,
            created_at: now,
            updated_at: now,
          },
        ],
        photos: [],
      },
      { status: 201 },
    );
  }),
  http.patch("http://api.test/fingersticks/:fingerstickId", async ({ params, request }) => {
    const body = (await request.json()) as Record<string, unknown>;
    return HttpResponse.json({
      id: params.fingerstickId,
      created_at: now,
      notes: null,
      ...body,
    });
  }),
  http.get("http://api.test/sensors", () =>
    HttpResponse.json([
      {
        id: "sensor-1",
        source: "manual",
        vendor: "Ottai",
        model: "Ottai",
        label: "Sensor A",
        started_at: "2026-04-28T00:00:00",
        ended_at: null,
        expected_life_days: 15,
        notes: null,
        created_at: now,
        updated_at: now,
      },
    ]),
  ),
  http.post("http://api.test/sensors", async ({ request }) => {
    const body = (await request.json()) as Record<string, unknown>;
    return HttpResponse.json(
      {
        id: "sensor-created",
        created_at: now,
        updated_at: now,
        ...body,
      },
      { status: 201 },
    );
  }),
  http.patch("http://api.test/sensors/:sensorId", async ({ params, request }) => {
    const body = (await request.json()) as Record<string, unknown>;
    return HttpResponse.json({
      id: params.sensorId,
      source: "manual",
      vendor: "Ottai",
      model: "Ottai",
      label: "Sensor A",
      started_at: "2026-04-28T00:00:00",
      ended_at: null,
      expected_life_days: 15,
      notes: null,
      created_at: now,
      updated_at: now,
      ...body,
    });
  }),
  http.get("http://api.test/sensors/:sensorId/quality", () =>
    HttpResponse.json({
      sensor: null,
      sensor_age_days: 1.4,
      fingerstick_count: 1,
      valid_calibration_points: 0,
      median_bias_mmol_l: null,
      mad_mmol_l: null,
      mard_percent: null,
      drift_mmol_l_per_day: 0,
      residual_mad_mmol_l: null,
      missing_data_pct: 8,
      suspected_compression_count: 0,
      noise_score: 4,
      quality_score: 72,
      confidence: "none",
      notes: [],
      active_model: null,
    }),
  ),
  http.post("http://api.test/sensors/:sensorId/recalculate-calibration", () =>
    HttpResponse.json({
      id: "calibration-1",
      sensor_session_id: "sensor-1",
      model_version: "display_linear_offset_v1",
      created_at: now,
      params_json: { can_normalize: false, b0: 0, b1: 0 },
      metrics_json: { fingerstick_count: 1, valid_calibration_points: 0 },
      confidence: "none",
      active: true,
    }),
  ),
  http.get("http://api.test/twin/params", () =>
    HttpResponse.json({
      id: "twin-params-1",
      icr_morning: 11.8,
      icr_day: 12.4,
      icr_evening: 13.1,
      morning_start_minutes: 360,
      day_start_minutes: 660,
      evening_start_minutes: 1080,
      isf: 2.05,
      dia_minutes: 270,
      carb_duration_minutes: 180,
      baseline_drift_per_hour: 0.02,
      last_fit_at: "2026-04-27T08:00:00.000Z",
      last_fit_data_from: "2026-03-28T00:00:00.000Z",
      last_fit_data_to: "2026-04-27T00:00:00.000Z",
      last_fit_train_window_count: 96,
      last_fit_holdout_window_count: 24,
      last_fit_train_mae_mmol: 1.32,
      last_fit_holdout_mae_mmol: 1.68,
      last_fit_method: "least_squares",
      last_fit_converged: true,
      updated_at: "2026-04-27T08:00:00.000Z",
      is_fitted: true,
      hint: "ready",
    }),
  ),
  http.patch("http://api.test/twin/params", async ({ request }) => {
    const body = (await request.json()) as Record<string, unknown>;
    return HttpResponse.json({
      id: "twin-params-1",
      icr_morning: body.icr_morning ?? 11.8,
      icr_day: body.icr_day ?? 12.4,
      icr_evening: body.icr_evening ?? 13.1,
      morning_start_minutes: body.morning_start_minutes ?? 360,
      day_start_minutes: body.day_start_minutes ?? 660,
      evening_start_minutes: body.evening_start_minutes ?? 1080,
      isf: body.isf ?? 2.05,
      dia_minutes: body.dia_minutes ?? 270,
      carb_duration_minutes: body.carb_duration_minutes ?? 180,
      baseline_drift_per_hour: body.baseline_drift_per_hour ?? 0.02,
      last_fit_at: now,
      last_fit_data_from: null,
      last_fit_data_to: null,
      last_fit_train_window_count: null,
      last_fit_holdout_window_count: null,
      last_fit_train_mae_mmol: null,
      last_fit_holdout_mae_mmol: null,
      last_fit_method: "manual",
      last_fit_converged: true,
      updated_at: now,
      is_fitted: true,
      hint: "ready",
    });
  }),
  http.get("http://api.test/twin/data/summary", ({ request }) => {
    const url = new URL(request.url);
    return HttpResponse.json({
      from_datetime: url.searchParams.get("from") ?? "2026-03-28T00:00:00",
      to_datetime: url.searchParams.get("to") ?? "2026-04-27T00:00:00",
      cgm_count: 8640,
      fingerstick_count: 42,
      meal_count: 78,
      insulin_count: 75,
      days_with_cgm: 30,
      first_cgm_at: "2026-03-28T00:00:00.000Z",
      last_cgm_at: "2026-04-27T00:00:00.000Z",
      ready_for_fit: true,
      fit_blockers: [],
    });
  }),
  http.post("http://api.test/twin/params/reset", () =>
    HttpResponse.json({
      id: "twin-params-1",
      icr_morning: null,
      icr_day: null,
      icr_evening: null,
      morning_start_minutes: 360,
      day_start_minutes: 660,
      evening_start_minutes: 1080,
      isf: null,
      dia_minutes: 270,
      carb_duration_minutes: 180,
      baseline_drift_per_hour: 0,
      last_fit_at: null,
      last_fit_data_from: null,
      last_fit_data_to: null,
      last_fit_train_window_count: null,
      last_fit_holdout_window_count: null,
      last_fit_train_mae_mmol: null,
      last_fit_holdout_mae_mmol: null,
      last_fit_method: "reset",
      last_fit_converged: null,
      updated_at: now,
      is_fitted: false,
      hint: "not_fitted",
    }),
  ),
  http.post("http://api.test/twin/fit", async ({ request }) => {
    const body = (await request.json()) as Record<string, unknown>;
    const previous = {
      id: "twin-params-1",
      icr_morning: null,
      icr_day: null,
      icr_evening: null,
      morning_start_minutes: 360,
      day_start_minutes: 660,
      evening_start_minutes: 1080,
      isf: null,
      dia_minutes: 270,
      carb_duration_minutes: 180,
      baseline_drift_per_hour: 0,
      last_fit_at: null,
      last_fit_data_from: null,
      last_fit_data_to: null,
      last_fit_train_window_count: null,
      last_fit_holdout_window_count: null,
      last_fit_train_mae_mmol: null,
      last_fit_holdout_mae_mmol: null,
      last_fit_method: null,
      last_fit_converged: null,
      updated_at: now,
      is_fitted: false,
      hint: "not_fitted",
    };
    const next = {
      ...previous,
      icr_morning: 11.8,
      icr_day: 12.4,
      icr_evening: 13.1,
      isf: 2.05,
      baseline_drift_per_hour: 0.02,
      last_fit_at: now,
      last_fit_data_from: body.data_from ?? "2026-03-28T00:00:00",
      last_fit_data_to: body.data_to ?? "2026-04-27T00:00:00",
      last_fit_train_window_count: 96,
      last_fit_holdout_window_count: 24,
      last_fit_train_mae_mmol: 1.32,
      last_fit_holdout_mae_mmol: 1.68,
      last_fit_method: "least_squares",
      last_fit_converged: true,
      is_fitted: true,
      hint: "ready",
    };
    return HttpResponse.json({
      applied: true,
      params: next,
      previous_params: previous,
      result: {
        icr_morning: 11.8,
        icr_day: 12.4,
        icr_evening: 13.1,
        isf: 2.05,
        baseline_drift_per_hour: 0.02,
        train_mae_mmol: 1.32,
        holdout_mae_mmol: 1.68,
        train_window_count: 96,
        holdout_window_count: 24,
        method: "least_squares",
        converged: true,
        iterations: 2,
        per_window_train_mae: [],
        per_window_holdout_mae: [],
        per_window_train_dates: [],
        per_window_holdout_dates: [],
      },
      notes: ["Подгонка является исследовательской моделью."],
    });
  }),
  http.get("http://api.test/twin/fit/history", () =>
    HttpResponse.json([
      {
        id: "twin-log-1",
        fit_at: "2026-04-27T08:00:00.000Z",
        data_from: "2026-03-28T00:00:00.000Z",
        data_to: "2026-04-27T00:00:00.000Z",
        params_snapshot: { icr_morning: 11.8, isf: 2.05 },
        train_window_count: 96,
        holdout_window_count: 24,
        train_mae_mmol: 1.32,
        holdout_mae_mmol: 1.68,
        method: "least_squares",
        converged: true,
        iterations: 74,
        notes: null,
      },
    ]),
  ),
  http.get("http://api.test/twin/curve", ({ request }) => {
    const url = new URL(request.url);
    const from = url.searchParams.get("from") ?? "2026-04-28T08:00:00";
    const to = url.searchParams.get("to") ?? "2026-04-28T10:00:00";
    return HttpResponse.json({
      from_datetime: from,
      to_datetime: to,
      points: [
        {
          timestamp: "2026-04-28T08:00:00",
          mmol: 6,
          ci_low: 6,
          ci_high: 6,
          confidence: 1,
          mode: "interpolation",
        },
        {
          timestamp: "2026-04-28T08:30:00",
          mmol: 7.1,
          ci_low: 6.8,
          ci_high: 7.4,
          confidence: 0.84,
          mode: "interpolation",
        },
        {
          timestamp: "2026-04-28T09:00:00",
          mmol: 8,
          ci_low: 8,
          ci_high: 8,
          confidence: 1,
          mode: "forecast",
        },
        {
          timestamp: "2026-04-28T09:30:00",
          mmol: 8.4,
          ci_low: 7.9,
          ci_high: 8.9,
          confidence: 0.83,
          mode: "forecast",
        },
      ],
      anchors: [
        { timestamp: "2026-04-28T08:00:00", mmol: 6, source: "fingerstick" },
        { timestamp: "2026-04-28T09:00:00", mmol: 8, source: "fingerstick" },
      ],
      food_events: [
        {
          timestamp: "2026-04-28T08:10:00",
          title: "Завтрак",
          carbs_g: 42,
          kcal: 380,
        },
      ],
      insulin_events: [
        {
          timestamp: "2026-04-28T08:08:00",
          insulin_units: 4,
          event_type: "Meal Bolus",
          notes: null,
        },
      ],
      params: {
        id: "twin-params-1",
        icr_morning: 11.8,
        icr_day: 12.4,
        icr_evening: 13.1,
        morning_start_minutes: 360,
        day_start_minutes: 660,
        evening_start_minutes: 1080,
        isf: 2.05,
        dia_minutes: 270,
        carb_duration_minutes: 180,
        baseline_drift_per_hour: 0.02,
        last_fit_at: "2026-04-27T08:00:00.000Z",
        last_fit_data_from: "2026-03-28T00:00:00.000Z",
        last_fit_data_to: "2026-04-27T00:00:00.000Z",
        last_fit_train_window_count: 96,
        last_fit_holdout_window_count: 24,
        last_fit_train_mae_mmol: 1.32,
        last_fit_holdout_mae_mmol: 1.68,
        last_fit_method: "least_squares",
        last_fit_converged: true,
        updated_at: "2026-04-27T08:00:00.000Z",
        is_fitted: true,
        hint: "ready",
      },
      notes: ["Цифровой двойник является исследовательской моделью."],
    });
  }),
  http.post("http://api.test/admin/recalculate", () =>
    HttpResponse.json({
      from_date: "2026-04-01",
      to_date: "2026-04-30",
      days_recalculated: 30,
    }),
  ),
);
